/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#003353",
        "on-secondary-fixed-variant": "#004f54",
        "on-surface-variant": "#bec7d4",
        "surface-container-highest": "#333539",
        "tertiary-fixed": "#f5e56b",
        "inverse-primary": "#00639a",
        "outline": "#88929d",
        "secondary-container": "#00f1fe",
        "surface-container": "#1e2024",
        "inverse-surface": "#e2e2e8",
        "tertiary-fixed-dim": "#d8c852",
        "on-primary-fixed-variant": "#004a76",
        "inverse-on-surface": "#2f3035",
        "primary-fixed": "#cee5ff",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "secondary-fixed-dim": "#00dbe7",
        "on-tertiary-fixed-variant": "#4f4700",
        "surface-variant": "#333539",
        "primary-fixed-dim": "#96ccff",
        "error": "#ffb4ab",
        "on-tertiary": "#373100",
        "on-error": "#690005",
        "primary-container": "#00a6ff",
        "surface-container-high": "#282a2e",
        "surface-dim": "#111318",
        "on-background": "#e2e2e8",
        "tertiary": "#d8c852",
        "surface-container-low": "#1a1c20",
        "on-secondary-container": "#006a70",
        "surface-tint": "#96ccff",
        "primary": "#96ccff",
        "on-tertiary-container": "#3c3600",
        "on-secondary-fixed": "#002022",
        "on-primary-fixed": "#001d32",
        "secondary-fixed": "#74f5ff",
        "secondary": "#ddfcff",
        "surface": "#111318",
        "background": "#111318",
        "error-container": "#93000a",
        "on-secondary": "#00363a",
        "on-surface": "#e2e2e8",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#201c00"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["JetBrains Mono", "monospace"]
      },
      borderRadius: {"DEFAULT": "0px", "lg": "0px", "xl": "0px", "full": "9999px"},
    },
  },
  plugins: [],
}
